import { createContext, useContext, useState, useEffect, useCallback } from 'react';
import axiosInstance from '../api/axiosInstance';

const LanguageContext = createContext(null);

export const SUPPORTED_LANGUAGES = {
  en: 'English',
  ta: 'தமிழ் (Tamil)',
  hi: 'हिंदी (Hindi)',
  te: 'తెలుగు (Telugu)',
  ml: 'മലയാളം (Malayalam)',
  kn: 'ಕನ್ನಡ (Kannada)',
};

// ── English labels (master copy) ─────────────────────────────
const EN_LABELS = {
  home:'Home', campaigns:'Campaigns', about:'About', contact:'Contact',
  login:'Login', logout:'Logout', register:'Register',
  dashboard:'Dashboard', myDonations:'My Donations', profile:'Profile',
  welcomeBack:'Welcome Back', signIn:'Sign In', createAccount:'Create Account',
  emailOrMobile:'Email or Mobile Number', password:'Password',
  confirmPassword:'Confirm Password', fullName:'Full Name',
  mobileNumber:'Mobile Number', address:'Address', rememberMe:'Remember me',
  forgotPassword:'Forgot password?', verifyEmail:'Verify Your Email',
  verifyMobile:'Verify Your Mobile', otpSentTo:'Enter the 6-digit code sent to your',
  verifyActivate:'Verify & Activate Account', resendCode:'Resend Code',
  welcomeBack2:'Welcome Back', totalDonated:'Total Donated',
  activeCampaigns:'Active Campaigns', campaignsBacked:'Campaigns Backed',
  myDetails:'My Details', donationSummary:'Donation Summary',
  upgradeMonthly:'Upgrade to Monthly Giving', managePlan:'Manage Plan',
  donateNow:'Donate', details:'Details', searchCampaigns:'Search campaigns…',
  mostUrgent:'Most Urgent', endingSoon:'Ending Soon', nearGoal:'Near Goal',
  daysLeft:'d left', goal:'Goal', raised:'raised',
  selectAmount:'Select Amount (₹)', customAmount:'Or enter custom amount',
  donateAnonymously:'Donate anonymously', continue:'Continue',
  paymentMethod:'Choose Payment Method', paySecurely:'Pay Securely',
  donationSuccessful:'Donation Successful!', saveReceipt:'Save Your Receipt',
  yesDownload:'Yes, Save Receipt', noThanks:'No Thanks',
  editProfile:'Edit Profile', saveChanges:'Save Changes', cancel:'Cancel',
  accountDetails:'Account Details', userId:'User ID', status:'Status',
  verified:'Active & Verified', updateFailed:'Update failed. Please try again.',
  updateSuccess:'Profile updated successfully!',
  monthlyGiving:'Monthly Giving', generalDonor:'General Donor',
  monthlyAmount:'Monthly Amount', donationDay:'Donation Day',
  nextPayment:'Next Payment', pause:'Pause', resume:'Resume',
  cancelSub:'Cancel', activate:'Activate Monthly Giving',
  notifications:'Notifications', noNotifications:'No notifications yet',
  markAllRead:'Mark all read', viewAll:'View all notifications',
  contactUs:'Contact Us', getInTouch:'Get in Touch', yourName:'Your Name',
  emailAddress:'Email Address', subject:'Subject', message:'Message',
  sendMessage:'Send Message', sending:'Sending…',
  messageSent:"Message sent! We'll respond within 24 hours.",
  loading:'Loading…', error:'Something went wrong', tryAgain:'Try Again',
  success:'Success', noData:'No data found', save:'Save', edit:'Edit',
  delete:'Delete', create:'Create', update:'Update', back:'Back',
  yes:'Yes', no:'No', confirm:'Confirm', close:'Close',
  total:'Total', amount:'Amount', date:'Date', receipt:'Receipt',
  campaign:'Campaign', method:'Method',
  // Extra keys used across pages
  emailAddress:'Email Address', signIn:'Sign In', signInToAccount:'Sign in to your CharityOrg account',
  createFreeAccount:'Create Free Account', joinSubtitle:'Join CharityOrg and start making a difference',
  alreadyAccount:'Already have an account?', creatingAccount:'Creating Account…',
  verify:'Verify', email:'Email', optional:'optional', signingIn:'Signing in…',
  emailRequired:'Email is required', passwordRequired:'Password is required',
  viewCampaigns:'View Campaigns', viewAllCampaigns:'View All Campaigns',
  heroSubtitle:'Join thousands of donors supporting verified campaigns. Every donation is tracked, every rupee accounted for — full financial transparency guaranteed.',
  transparentGiving:'Transparent & Secure Giving', featuredCampaigns:'Featured Campaigns',
  featuredSubtitle:'Support causes that matter most right now',
  activeCampaigns:'Active Campaigns', totalDonors:'Total Donors',
  amountRaised:'Amount Raised (₹)', volunteers:'Volunteers',
  fullTransparency:'Full', transparency:'Transparency',
  transparencyDesc:'We believe every donor deserves to know exactly where their money goes. Track fund allocations in real time.',
  realtimeTracking:'Real-time Tracking', realtimeTrackingDesc:'Every donation is tracked from receipt to utilization.',
  fundReports:'Fund Allocation Reports', fundReportsDesc:'Detailed breakdown of how funds are spent per campaign.',
  securePayments:'Secure Payments', securePaymentsDesc:'Razorpay-powered payments with bank-level security.',
  taxReceipts:'Tax Receipts', taxReceiptsDesc:'Auto-generated 80G-eligible receipts for every donation.',
  fundUtilization:'Fund Utilization', directAid:'Direct Aid', operations:'Operations',
  admin:'Admin', reserve:'Reserve',
  successStories:'Success', stories:'Stories',
  successStoriesSubtitle:'Real impact from real donations',
  story1Title:'500 Families Got Clean Water', story2Title:'200 Scholarships Awarded', story3Title:'1000+ Free Health Checkups',
  story1Desc:'Thanks to donors like you, 500 families in Maharashtra now have access to safe drinking water.',
  story2Desc:'Brilliant but underprivileged students can now pursue their dreams with full scholarships.',
  story3Desc:'Our medical camp initiative provided free checkups and medicines to over 1000 people.',
  donorsContributed:'donors contributed', upcoming:'Upcoming', events:'Events',
  eventsSubtitle:'Join us and make a difference in person',
  ctaTitle:'Ready to', ctaHighlight:'Make an Impact?',
  ctaSubtitle:'Join 10,000+ donors who trust CharityOrg for transparent, impactful giving.',
  getStarted:'Get Started Free', browseCampaigns:'Browse Campaigns',
  // About page
  aboutSubtitle:'Empowering communities through transparent giving since 2024',
  ourMission:'Our Mission', ourValues:'Our Values', meetThe:'Meet the', team:'Team',
  missionDesc1:'CharityOrg was founded with a simple but powerful mission — to eliminate the trust gap between donors and charities.',
  missionDesc2:'Through technology, we connect verified campaigns with generous donors, ensuring funds reach those who need them most with full financial accountability.',
  value1:'Transparency — Every rupee tracked publicly', value2:'Security — Bank-grade payment encryption',
  value3:'Impact — Measurable outcomes for every campaign', value4:'Community — Building bridges between givers & receivers',
  execDirector:'Executive Director', techLead:'Tech Lead', campaignMgr:'Campaign Manager', financeOfficer:'Finance Officer',
  supportCampaign:'Support a Campaign',
  // Campaigns page
  allCampaigns:'All Campaigns', chooseCause:'Choose a cause and make a difference today',
  newestFirst:'Newest First', mostFunded:'Most Funded',
  showing:'Showing', of:'of', noCampaignsFound:'No campaigns found', tryAdjust:'Try adjusting your search or filters',
  viewAndDonate:'View & Donate',
  // User pages
  myPlan:'My Plan', notSet:'Not set', mobile:'Mobile', role:'Role', userId:'User ID',
  upgradeMonthlyDesc:'Upgrade to Monthly Giving for automated donations, pre-donation reminders, and monthly receipts.',
  clear:'Clear', myProfile:'My', profileDesc:'Manage your personal information and account settings',
  editPersonalDetails:'Edit Personal Details', saving:'Saving',
  viewAllDonations:'View All Donations',
  totalDonations:'Total Donations', successful:'Successful', totalContributed:'Total Contributed',
  trackContributions:'Track all your contributions and download receipts', donations:'Donations',
  upgradeDesc:'Set up automatic monthly donations with reminders & receipts',
  // Footer
  quickLinks:'Quick Links', forDonors:'For Donors', days:'days',
  // Hero & misc
  changeLines:'Change Lives with', everyRupee:'Every Rupee', youGive:'You Give', all:'All',
  // VerifyAccount / VerifyOtp keys
  accountVerified:'Account Verified!', redirectingToDashboard:'Redirecting you to your dashboard…',
  backToRegister:'← Back to Register', backToLogin:'← Back to Login',
  verifyYourMobile:'Verify Your Mobile', verifyYourEmail:'Verify Your Email',
  verifyYourIdentity:'Verify Your Identity',
  enterCodeSentToChannel:'Enter the 6-digit code sent to your',
  mobileNumber:'Mobile Number', emailAddress:'Email Address',
  verificationRequiredOnce:'This verification is required only once',
  verifying:'Verifying…', verifyActivateAccount:'✓ Verify & Activate Account',
  verifySignIn:'✓ Verify & Sign In',
  enterMoreDigits:'Enter', moreDigits:'more digits',
  didNotReceiveCode:"Didn't receive the code?",
  resendIn:'Resend in', resendCode:'↺ Resend Code', resendOtp:'↺ Resend OTP',
  sending:'Sending…', weSentCodeTo:'We sent a 6-digit code to',
  expiresIn5Min:'⏱ Expires in 5 min', max3Attempts:'🔄 Max 3 attempts',
  oneTimeOnly:'🔑 One-time only', checkYourInbox:'📧 Check your inbox',
  // Unauthorized
  accessDenied:'Access Denied', noPermissionToView:"You don't have permission to view this page.",
  goHome:'Go Home',
  // CampaignDetails
  backToCampaigns:'← Back to Campaigns', urgency:'Urgency',
  startDate:'Start Date', endDate:'End Date', beneficiaries:'Beneficiaries',
  createdBy:'Created By', remaining:'Remaining', daysLeft:'d left',
  supportCampaign:'Support This Campaign', raised:'Raised', goal:'Goal',
  donateNow:'Donate Now', loginAsDonorToDonate:'Login as a Donor to donate to this campaign.',
  loginToDonate:'Login to Donate', registerAsDonor:'Register as Donor',
  securePaymentViaRazorpay:'Secure payment via Razorpay',
  receiptAutoGenerated:'80G receipt auto-generated',
  transparentFundUsage:'100% transparent fund usage',
  // SubscriptionOnboarding
  welcomeTo:'Welcome to', howLikeToContribute:'How would you like to contribute? You can change this anytime.',
  generalDonorDesc:'Make one-time donations whenever you wish. No recurring payments, no commitments.',
  oneTimeDonations:'One-time donations', noRecurringCharges:'No recurring charges',
  donateAnyCampaign:'Donate any campaign', fullDonationHistory:'Full donation history',
  settingUp:'Setting up…', continueAsGeneralDonor:'Continue as General Donor',
  recommended:'RECOMMENDED', monthlyGivingDesc:'Set a recurring monthly donation. Automated, consistent impact every month.',
  automaticMonthlyDonations:'Automatic monthly donations', preDonationReminders:'Pre-donation reminders',
  monthlyReceipts:'Monthly receipts', pauseResumeAnytime:'Pause / resume anytime',
  cancelAnytime:'Cancel anytime', setUpMonthlyGiving:'Set Up Monthly Giving',
  setUpMonthlyGivingTitle:'Set Up Monthly Giving',
  chooseMonthlyAmount:'Choose your monthly amount, donation date, and campaign.',
  monthlyAmount:'Monthly Amount', customAmount:'Custom amount',
  minimumMonthlyAmountInfo:'Minimum ₹50/month', donationDayOfMonth:'Donation Day of Month',
  dayOfEveryMonth:'Day {day} of every month', campaignOptional:'Campaign (optional)',
  supportAllActiveCampaigns:'— Support all active campaigns —',
  monthlyGivingSummary:'Your Monthly Giving Summary',
  monthlyGivingSummaryDesc:'will be donated on day {day} of each month',
  toCampaign:'to', acrossActiveCampaigns:'across active campaigns',
  skipGoGeneral:'Skip, go General', activating:'Activating…',
  activateMonthlyGiving:'Activate Monthly Giving',
  skipForNowDecideLater:'Skip for now — decide later',
  // SubscriptionManagement
  subscription:'Subscription', management:'Management',
  manageDonationPlanPreferences:'Manage your donation plan and preferences',
  active:'Active', paused:'Paused', cancelled:'Cancelled',
  generalDonorDescShort:'One-time donations — no recurring charges',
  upgradeToMonthlyGiving:'Upgrade to Monthly Giving', month:'month',
  allActiveCampaigns:'All Active Campaigns', dayOfMonth:'Day {day} of month',
  nextDonation:'Next Donation', lastDonation:'Last Donation', notYet:'Not yet',
  manageSubscription:'Manage Subscription', editAmount:'Edit Amount',
  changeDate:'Change Date', pauseSubscription:'Pause Subscription',
  resumeSubscription:'Resume Subscription', cancelSubscription:'Cancel Subscription',
  pauseConfirmPrompt:'Pause your monthly subscription?',
  cancelConfirmPrompt:'Cancel your Monthly Giving subscription?\nYou can upgrade again anytime.',
  whyMonthlyGiving:'Why Monthly Giving?', automatedDonations:'Automated donations',
  noNeedToRemember:'No need to remember — we handle it.',
  emailReminderBeforeDonation:'Email reminder before every donation.',
  automaticReceipts:'Automatic 80G tax receipts.',
  fullControl:'Full control', pauseResumeCancelAnytime:'Pause, resume or cancel anytime.',
  upgradeMonthlyDesc:'Set your monthly amount and preferred date.',
  donationDay:'Donation Day', editMonthlyAmount:'Edit Monthly Amount',
  newMonthlyAmount:'New Monthly Amount', updateAmount:'Update Amount',
  changeDonationDate:'Change Donation Date', newDonationDay:'New Donation Day',
  updateDate:'Update Date',
  // DonationFlow
  payment:'Payment', amount:'Amount',
  offlineDemoModeInfo:'Offline Demo Mode — no real payment processed',
  donateToCampaign:'Donate to Campaign', selectAmount:'Select Amount (₹)',
  customAmountPlaceholder:'Or enter custom amount',
  donateAnonymously:'Donate anonymously', continueSelectPayment:'Continue → Select Payment',
  back:'← Back', choosePaymentMethod:'Choose Payment Method',
  donatingTo:'Donating {amount} to {campaign}',
  demoModeNoRealCharge:'Demo mode — no real charge made',
  paymentsSecuredByRazorpay:'Payments secured by Razorpay. Card data never stored.',
  processing:'Processing…', payDemo:'Pay {amount} (Demo)',
  paySecurely:'Pay {amount} Securely 🔒',
  receiptThankYou:'Thank you, {name}! Your generosity makes a difference. 💜',
  paymentMethod:'Payment Method', receiptNo:'Receipt No.',
  transactionId:'Transaction ID', dateTime:'Date & Time',
  paymentConfirmed:'Payment Confirmed', taxExempt80G:'80G Exempt',
  taxDeductibleYes:'Yes — Tax Deductible', saveYourReceipt:'Save Your Receipt',
  saveReceiptPrompt:'Would you like to save a screenshot of your donation receipt? It will be downloaded as a PNG image to your device.',
  savedDownloadAgain:'✓ Saved! Download Again',
  yesSaveReceiptScreenshot:'Yes, Save Receipt Screenshot',
  receiptSavedDownloadsFolder:'Receipt saved to your Downloads folder',
  donateAgain:'Donate Again', thankYou:'Thank You!',
  donationToConfirmed:'Your donation to {campaign} has been confirmed.',
  receiptSentToEmail:'Receipt {receipt} has been sent to your registered email.',
  viewMyDonations:'View My Donations', backToDashboard:'Back to Dashboard',
  upi:'UPI', creditCard:'Credit Card', debitCard:'Debit Card', netBanking:'Net Banking',
  // Contact page extra
  contactSubtitle:"We'd love to hear from you. Reach out anytime!",
  loggedInAs:'Logged in as {name}',
  messageLinkedToAccount:'Your message will be linked to your account. You can also save your contact info to your profile.',
  savePhoneAddressToProfile:'Save phone & address to my profile',
  tenDigitNumber:'10-digit number', addressCity:'Address / City', cityState:'City, State',
  // Profile — Change Password section
  changePassword:'Change Password',
  changePasswordDesc:'Update your password. An email confirmation will be sent after each change.',
  currentPassword:'Current Password', currentPasswordPlaceholder:'Your current password',
  newPassword:'New Password', confirmNewPassword:'Confirm New Password',
  reEnterNewPassword:'Re-enter new password',
  passwordsMatch:'Passwords match',
  passwordRequirements:'Must be 8+ chars with uppercase, lowercase, digit and special character (@$!%*?&)',
  updatePassword:'Update Password',
  // Profile — Preferred Language
  preferredLanguage:'Preferred Language',
};

// ── Built-in static translations (work WITHOUT Gemini) ────────
const STATIC_TRANSLATIONS = {
  ta: {
    home:'முகப்பு', campaigns:'பிரச்சாரங்கள்', about:'பற்றி', contact:'தொடர்பு',
    login:'உள்நுழைவு', logout:'வெளியேறு', register:'பதிவு செய்',
    dashboard:'டாஷ்போர்டு', myDonations:'என் நன்கொடைகள்', profile:'சுயவிவரம்',
    welcomeBack:'மீண்டும் வரவேற்கிறோம்', signIn:'உள்நுழைக',
    createAccount:'கணக்கு உருவாக்கு', password:'கடவுச்சொல்',
    fullName:'முழு பெயர்', address:'முகவரி', rememberMe:'என்னை நினைவில் வை',
    forgotPassword:'கடவுச்சொல் மறந்தீர்களா?',
    dashboard:'டாஷ்போர்டு', totalDonated:'மொத்த நன்கொடை',
    activeCampaigns:'செயல்பாட்டு பிரச்சாரங்கள்', myDetails:'என் விவரங்கள்',
    donateNow:'நன்கொடை செய்', details:'விவரங்கள்',
    searchCampaigns:'பிரச்சாரங்களை தேடுங்கள்…',
    mostUrgent:'மிகவும் அவசரமானது', endingSoon:'விரைவில் முடிகிறது',
    selectAmount:'தொகை தேர்ந்தெடுங்கள்', donateAnonymously:'அனாமதேயமாக நன்கொடை',
    continue:'தொடரவும்', paymentMethod:'கட்டண முறை தேர்ந்தெடுங்கள்',
    donationSuccessful:'நன்கொடை வெற்றிகரமாக பதிவு!', noThanks:'வேண்டாம்',
    editProfile:'சுயவிவரத்தை திருத்து', saveChanges:'மாற்றங்களை சேமி',
    cancel:'ரத்து செய்', accountDetails:'கணக்கு விவரங்கள்',
    notifications:'அறிவிப்புகள்', noNotifications:'அறிவிப்புகள் இல்லை',
    markAllRead:'அனைத்தையும் படித்ததாக குறி',
    contactUs:'தொடர்பு கொள்ளுங்கள்', yourName:'உங்கள் பெயர்',
    subject:'தலைப்பு', message:'செய்தி', sendMessage:'செய்தி அனுப்பு',
    sending:'அனுப்புகிறோம்…', loading:'ஏற்றுகிறோம்…',
    error:'பிழை ஏற்பட்டது', save:'சேமி', edit:'திருத்து',
    delete:'நீக்கு', create:'உருவாக்கு', update:'புதுப்பி', back:'பின்னால்',
    yes:'ஆம்', no:'இல்லை', confirm:'உறுதிப்படுத்து', close:'மூடு',
    total:'மொத்தம்', amount:'தொகை', date:'தேதி', status:'நிலை',
    monthlyGiving:'மாதாந்திர நன்கொடை', generalDonor:'பொது நன்கொடையாளர்',
    pause:'இடைநிறுத்து', resume:'தொடரவும்', cancelSub:'ரத்து செய்',
    verifyEmail:'உங்கள் மின்னஞ்சலை சரிபார்க்கவும்',
    upgradeMonthly:'மாதாந்திர நன்கொடைக்கு மேம்படுத்து',
    success:'வெற்றி', noData:'தரவு இல்லை', receipt:'ரசீது',
    login:'உள்நுழைவு', register:'பதிவு செய்', logout:'வெளியேறு',
    // Extra new keys
    emailAddress:'மின்னஞ்சல் முகவரி', signIn:'உள்நுழைக',
    signInToAccount:'உங்கள் CharityOrg கணக்கில் உள்நுழையுங்கள்',
    createFreeAccount:'இலவச கணக்கை உருவாக்கு', alreadyAccount:'ஏற்கனவே கணக்கு உள்ளதா?',
    viewCampaigns:'பிரச்சாரங்களை காண்க', viewAllCampaigns:'அனைத்து பிரச்சாரங்களும்',
    raised:'திரட்டப்பட்டது', goal:'இலக்கு', daysLeft:'நாள் மீதம்',
    activeCampaigns:'செயல்பாட்டு பிரச்சாரங்கள்', totalDonors:'மொத்த நன்கொடையாளர்கள்',
    volunteers:'தொண்டர்கள்', browseCampaigns:'பிரச்சாரங்களை உலாவுங்கள்',
    getStarted:'இப்போது தொடங்குங்கள்', ourMission:'எங்கள் நோக்கம்',
    ourValues:'எங்கள் மதிப்புகள்', meetThe:'அணியினை சந்தியுங்கள்',
    team:'குழு', allCampaigns:'அனைத்து பிரச்சாரங்கள்',
    chooseCause:'ஒரு காரணத்தை தேர்ந்தெடுங்கள்', newestFirst:'புதிதாக முதலில்',
    mostFunded:'அதிகம் நிதி பெற்றது', showing:'காட்டுகிறது', of:'இல்',
    noCampaignsFound:'பிரச்சாரங்கள் இல்லை', tryAdjust:'தேடலை சரிசெய்யுங்கள்',
    viewAndDonate:'பார்க்க & நன்கொடை', myPlan:'என் திட்டம்',
    userId:'பயனர் ID', mobile:'மொபைல்', role:'பாத்திரம்',
    clear:'அழி', profileDesc:'உங்கள் தனிப்பட்ட தகவலை நிர்வகிக்கவும்',
    editPersonalDetails:'தனிப்பட்ட விவரங்களை திருத்து',
    saving:'சேமிக்கிறோம்', viewAllDonations:'அனைத்து நன்கொடைகளையும் பார்க்க',
    totalDonations:'மொத்த நன்கொடைகள்', successful:'வெற்றிகரமான',
    totalContributed:'மொத்தம் பங்களித்தது',
    trackContributions:'உங்கள் பங்களிப்புகளை கண்காணிக்கவும்', donations:'நன்கொடைகள்',
    quickLinks:'விரைவு இணைப்புகள்', forDonors:'நன்கொடையாளர்களுக்கு',
    days:'நாட்கள்', verified:'சரிபார்க்கப்பட்டது', amount:'தொகை',
    campaign:'பிரச்சாரம்', method:'முறை', date:'தேதி',
    donationSummary:'நன்கொடை சுருக்கம்', accountDetails:'கணக்கு விவரங்கள்',
    managePlan:'திட்டத்தை நிர்வகி',
    campaignsBacked:'ஆதரித்த பிரச்சாரங்கள்',
    changeLines:'வாழ்க்கைகளை மாற்றுங்கள்', everyRupee:'ஒவ்வொரு ரூபாயிலும்',
    youGive:'கொடுக்கும்', all:'அனைத்தும்',
    // New keys
    accountVerified:'கணக்கு சரிபார்க்கப்பட்டது!', redirectingToDashboard:'உங்கள் டாஷ்போர்டுக்கு திருப்பி விடுகிறோம்…',
    backToRegister:'← பதிவுக்கு திரும்பு', backToLogin:'← உள்நுழைவுக்கு திரும்பு',
    verifyYourMobile:'உங்கள் மொபைலை சரிபார்க்கவும்', verifyYourEmail:'உங்கள் மின்னஞ்சலை சரிபார்க்கவும்',
    verifyYourIdentity:'உங்கள் அடையாளத்தை சரிபார்க்கவும்',
    enterCodeSentToChannel:'அனுப்பப்பட்ட 6-இலக்க குறியீட்டை உள்ளிடவும்',
    verificationRequiredOnce:'இந்த சரிபார்ப்பு ஒரே ஒரு முறை மட்டுமே தேவை',
    verifying:'சரிபார்க்கிறோம்…', verifyActivateAccount:'✓ சரிபார்த்து கணக்கை செயல்படுத்து',
    verifySignIn:'✓ சரிபார்த்து உள்நுழைக', enterMoreDigits:'உள்ளிடவும்', moreDigits:'இலக்கங்கள் மேலும்',
    didNotReceiveCode:'குறியீடு பெறவில்லையா?', resendIn:'மீண்டும் அனுப்ப',
    resendOtp:'↺ OTP மீண்டும் அனுப்பு', weSentCodeTo:'6-இலக்க குறியீடு அனுப்பப்பட்டது',
    expiresIn5Min:'⏱ 5 நிமிடத்தில் காலாவதி', max3Attempts:'🔄 அதிகபட்சம் 3 முயற்சிகள்',
    oneTimeOnly:'🔑 ஒரே ஒரு முறை மட்டும்', checkYourInbox:'📧 உங்கள் இன்பாக்ஸ் பாருங்கள்',
    accessDenied:'அணுகல் மறுக்கப்பட்டது', noPermissionToView:'இந்த பக்கத்தை பார்க்க உங்களுக்கு அனுமதி இல்லை.',
    goHome:'முகப்புக்கு செல்', backToCampaigns:'← பிரச்சாரங்களுக்கு திரும்பு',
    urgency:'அவசரத்தன்மை', startDate:'தொடக்க தேதி', endDate:'இறுதி தேதி',
    beneficiaries:'பயனாளர்கள்', createdBy:'உருவாக்கியவர்', remaining:'மீதம்',
    supportCampaign:'இந்த பிரச்சாரத்தை ஆதரிக்கவும்',
    loginAsDonorToDonate:'நன்கொடை செய்ய நன்கொடையாளராக உள்நுழையுங்கள்.',
    loginToDonate:'நன்கொடை செய்ய உள்நுழைக', registerAsDonor:'நன்கொடையாளராக பதிவு செய்',
    securePaymentViaRazorpay:'Razorpay வழி பாதுகாப்பான கட்டணம்',
    receiptAutoGenerated:'80G ரசீது தானாக உருவாகும்', transparentFundUsage:'100% வெளிப்படையான நிதி பயன்பாடு',
    welcomeTo:'வரவேற்கிறோம்', howLikeToContribute:'எப்படி பங்களிக்க விரும்புகிறீர்கள்? எப்போதும் மாற்றலாம்.',
    generalDonorDesc:'விரும்பும்போது ஒருமுறை நன்கொடை செய்யுங்கள். தொடர் கட்டணங்கள் இல்லை.',
    oneTimeDonations:'ஒருமுறை நன்கொடைகள்', noRecurringCharges:'தொடர் கட்டணங்கள் இல்லை',
    donateAnyCampaign:'எந்த பிரச்சாரத்திலும் நன்கொடை', fullDonationHistory:'முழு நன்கொடை வரலாறு',
    settingUp:'அமைக்கிறோம்…', continueAsGeneralDonor:'பொது நன்கொடையாளராக தொடரவும்',
    recommended:'பரிந்துரைக்கப்படுகிறது',
    monthlyGivingDesc:'மாதாந்திர நன்கொடையை அமைக்கவும். தானியங்கி, நிலையான தாக்கம்.',
    automaticMonthlyDonations:'தானியங்கி மாதாந்திர நன்கொடைகள்',
    monthlyReceipts:'மாதாந்திர ரசீதுகள்', pauseResumeAnytime:'எப்போதும் இடைநிறுத்தலாம்/தொடரலாம்',
    cancelAnytime:'எப்போதும் ரத்து செய்யலாம்', setUpMonthlyGiving:'மாதாந்திர நன்கொடையை அமை',
    setUpMonthlyGivingTitle:'மாதாந்திர நன்கொடையை அமைக்கவும்',
    chooseMonthlyAmount:'உங்கள் மாதாந்திர தொகை, தேதி மற்றும் பிரச்சாரத்தை தேர்வு செய்யுங்கள்.',
    minimumMonthlyAmountInfo:'குறைந்தபட்சம் ₹50/மாதம்', donationDayOfMonth:'நன்கொடை நாள்',
    dayOfEveryMonth:'ஒவ்வொரு மாதமும் {day}வது நாள்', campaignOptional:'பிரச்சாரம் (விருப்பத்தேர்வு)',
    supportAllActiveCampaigns:'— அனைத்து செயல்பாட்டு பிரச்சாரங்களையும் ஆதரிக்கவும் —',
    monthlyGivingSummary:'உங்கள் மாதாந்திர நன்கொடை சுருக்கம்',
    monthlyGivingSummaryDesc:'ஒவ்வொரு மாதமும் {day}வது நாள் நன்கொடை செய்யப்படும்',
    toCampaign:'க்கு', acrossActiveCampaigns:'செயல்பாட்டு பிரச்சாரங்களில்',
    skipGoGeneral:'தவிர்க்கவும், பொது நன்கொடையாளராக செல்லுங்கள்',
    activating:'செயல்படுத்துகிறோம்…', activateMonthlyGiving:'மாதாந்திர நன்கொடையை செயல்படுத்து',
    skipForNowDecideLater:'இப்போது தவிர்க்கவும் — பின்னர் முடிவு செய்யுங்கள்',
    subscription:'சந்தா', management:'மேலாண்மை',
    manageDonationPlanPreferences:'உங்கள் நன்கொடை திட்டத்தை நிர்வகிக்கவும்',
    active:'செயல்பாட்டில்', paused:'இடைநிறுத்தப்பட்டது', cancelled:'ரத்து செய்யப்பட்டது',
    generalDonorDescShort:'ஒருமுறை நன்கொடைகள் — தொடர் கட்டணங்கள் இல்லை',
    upgradeToMonthlyGiving:'மாதாந்திர நன்கொடைக்கு மேம்படுத்து', month:'மாதம்',
    allActiveCampaigns:'அனைத்து செயல்பாட்டு பிரச்சாரங்கள்',
    dayOfMonth:'{day}வது நாள்', nextDonation:'அடுத்த நன்கொடை',
    lastDonation:'கடைசி நன்கொடை', notYet:'இன்னும் இல்லை',
    manageSubscription:'சந்தாவை நிர்வகி', editAmount:'தொகையை திருத்து',
    changeDate:'தேதியை மாற்று', pauseSubscription:'சந்தாவை இடைநிறுத்து',
    resumeSubscription:'சந்தாவை மீண்டும் தொடரவும்', cancelSubscription:'சந்தாவை ரத்து செய்',
    whyMonthlyGiving:'மாதாந்திர நன்கொடை ஏன்?', automatedDonations:'தானியங்கி நன்கொடைகள்',
    noNeedToRemember:'நினைவில் வைக்க வேண்டாம் — நாங்கள் கவனிக்கிறோம்.',
    emailReminderBeforeDonation:'ஒவ்வொரு நன்கொடைக்கு முன் மின்னஞ்சல் நினைவூட்டல்.',
    automaticReceipts:'தானியங்கி 80G வரி ரசீதுகள்.',
    fullControl:'முழு கட்டுப்பாடு', pauseResumeCancelAnytime:'எப்போதும் இடைநிறுத்தலாம், தொடரலாம் அல்லது ரத்து செய்யலாம்.',
    upgradeMonthlyDesc:'உங்கள் மாதாந்திர தொகை மற்றும் விருப்பமான தேதியை அமைக்கவும்.',
    donationDay:'நன்கொடை நாள்', editMonthlyAmount:'மாதாந்திர தொகையை திருத்து',
    newMonthlyAmount:'புதிய மாதாந்திர தொகை', updateAmount:'தொகையை புதுப்பி',
    changeDonationDate:'நன்கொடை தேதியை மாற்று', newDonationDay:'புதிய நன்கொடை நாள்', updateDate:'தேதியை புதுப்பி',
    payment:'கட்டணம்', offlineDemoModeInfo:'ஆஃப்லைன் டெமோ பயன்முறை — உண்மையான கட்டணம் செயலாக்கப்படவில்லை',
    donateToCampaign:'பிரச்சாரத்திற்கு நன்கொடை', selectAmount:'தொகை தேர்ந்தெடுங்கள் (₹)',
    customAmountPlaceholder:'அல்லது தனிப்பயன் தொகை உள்ளிடவும்',
    continueSelectPayment:'தொடரவும் → கட்டணம் தேர்வு செய்யவும்',
    choosePaymentMethod:'கட்டண முறையை தேர்ந்தெடுங்கள்',
    donatingTo:'{amount} நன்கொடை செய்கிறீர்கள் {campaign} க்கு',
    demoModeNoRealCharge:'டெமோ பயன்முறை — உண்மையான கட்டணம் இல்லை',
    paymentsSecuredByRazorpay:'Razorpay மூலம் கட்டணங்கள் பாதுகாக்கப்படுகின்றன.',
    processing:'செயலாக்குகிறோம்…', payDemo:'{amount} செலுத்துங்கள் (டெமோ)',
    paySecurely:'{amount} பாதுகாப்பாக செலுத்துங்கள் 🔒',
    receiptThankYou:'நன்றி, {name}! உங்கள் தாராள மனப்பான்மை வித்தியாசத்தை ஏற்படுத்துகிறது. 💜',
    receiptNo:'ரசீது எண்.', transactionId:'பரிவர்த்தனை ID', dateTime:'தேதி & நேரம்',
    paymentConfirmed:'கட்டணம் உறுதிப்படுத்தப்பட்டது', taxExempt80G:'80G விலக்கு',
    taxDeductibleYes:'ஆம் — வரி கழிக்கக்கூடியது', saveYourReceipt:'உங்கள் ரசீதை சேமிக்கவும்',
    saveReceiptPrompt:'உங்கள் நன்கொடை ரசீதின் ஸ்கிரீன்ஷாட்டை சேமிக்க விரும்புகிறீர்களா?',
    savedDownloadAgain:'✓ சேமிக்கப்பட்டது! மீண்டும் பதிவிறக்கவும்',
    yesSaveReceiptScreenshot:'ஆம், ரசீது ஸ்கிரீன்ஷாட்டை சேமி',
    receiptSavedDownloadsFolder:'ரசீது உங்கள் பதிவிறக்கங்கள் கோப்புறையில் சேமிக்கப்பட்டது',
    donateAgain:'மீண்டும் நன்கொடை செய்', thankYou:'நன்றி!',
    donationToConfirmed:'உங்கள் {campaign} க்கான நன்கொடை உறுதிப்படுத்தப்பட்டது.',
    receiptSentToEmail:'ரசீது {receipt} உங்கள் மின்னஞ்சலுக்கு அனுப்பப்பட்டது.',
    viewMyDonations:'என் நன்கொடைகளை பார்க்க', backToDashboard:'டாஷ்போர்டுக்கு திரும்பு',
    upi:'UPI', creditCard:'கிரெடிட் கார்டு', debitCard:'டெபிட் கார்டு', netBanking:'நெட் பேங்கிங்',
    contactSubtitle:'உங்களிடமிருந்து கேட்க விரும்புகிறோம். எப்போது வேண்டுமானாலும் தொடர்பு கொள்ளுங்கள்!',
    loggedInAs:'{name} ஆக உள்நுழைந்துள்ளீர்கள்',
    messageLinkedToAccount:'உங்கள் செய்தி உங்கள் கணக்குடன் இணைக்கப்படும்.',
    savePhoneAddressToProfile:'மொபைல் & முகவரியை சுயவிவரத்தில் சேமி',
    tenDigitNumber:'10-இலக்க எண்', addressCity:'முகவரி / நகர்', cityState:'நகர், மாநிலம்',
    // Password change
    changePassword:'கடவுச்சொல்லை மாற்று',
    changePasswordDesc:'உங்கள் கடவுச்சொல்லை புதுப்பிக்கவும். ஒவ்வொரு மாற்றத்திற்கும் மின்னஞ்சல் உறுதிப்படுத்தல் அனுப்பப்படும்.',
    currentPassword:'தற்போதைய கடவுச்சொல்', currentPasswordPlaceholder:'உங்கள் தற்போதைய கடவுச்சொல்',
    newPassword:'புதிய கடவுச்சொல்', confirmNewPassword:'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    reEnterNewPassword:'புதிய கடவுச்சொல்லை மீண்டும் உள்ளிடவும்',
    passwordsMatch:'கடவுச்சொற்கள் பொருந்துகின்றன',
    passwordRequirements:'குறைந்தது 8 எழுத்துகள்: பெரிய, சிறிய, எண் மற்றும் சிறப்பு எழுத்து',
    updatePassword:'கடவுச்சொல்லை புதுப்பி',
    preferredLanguage:'விருப்பமான மொழி',
  },
  hi: {
    home:'होम', campaigns:'अभियान', about:'के बारे में', contact:'संपर्क',
    login:'लॉगिन', logout:'लॉगआउट', register:'पंजीकरण',
    dashboard:'डैशबोर्ड', myDonations:'मेरे दान', profile:'प्रोफ़ाइल',
    welcomeBack:'वापस स्वागत है', signIn:'साइन इन करें',
    createAccount:'खाता बनाएं', password:'पासवर्ड',
    fullName:'पूरा नाम', address:'पता', rememberMe:'मुझे याद रखें',
    forgotPassword:'पासवर्ड भूल गए?',
    totalDonated:'कुल दान', activeCampaigns:'सक्रिय अभियान',
    myDetails:'मेरी जानकारी', donateNow:'दान करें', details:'विवरण',
    searchCampaigns:'अभियान खोजें…',
    mostUrgent:'सबसे जरूरी', endingSoon:'जल्द समाप्त',
    selectAmount:'राशि चुनें', donateAnonymously:'गुमनाम दान करें',
    continue:'जारी रखें', paymentMethod:'भुगतान विधि चुनें',
    donationSuccessful:'दान सफल!', noThanks:'नहीं धन्यवाद',
    editProfile:'प्रोफ़ाइल संपादित करें', saveChanges:'परिवर्तन सहेजें',
    cancel:'रद्द करें', accountDetails:'खाता विवरण',
    notifications:'सूचनाएं', noNotifications:'कोई सूचना नहीं',
    markAllRead:'सभी पढ़ा हुआ चिह्नित करें',
    contactUs:'संपर्क करें', yourName:'आपका नाम',
    subject:'विषय', message:'संदेश', sendMessage:'संदेश भेजें',
    sending:'भेज रहे हैं…', loading:'लोड हो रहा है…',
    error:'कुछ गलत हुआ', save:'सहेजें', edit:'संपादित करें',
    delete:'हटाएं', create:'बनाएं', update:'अपडेट करें', back:'वापस',
    yes:'हां', no:'नहीं', confirm:'पुष्टि करें', close:'बंद करें',
    total:'कुल', amount:'राशि', date:'तारीख', status:'स्थिति',
    monthlyGiving:'मासिक दान', generalDonor:'सामान्य दाता',
    pause:'रोकें', resume:'फिर शुरू करें', cancelSub:'रद्द करें',
    verifyEmail:'अपना ईमेल सत्यापित करें',
    upgradeMonthly:'मासिक दान में अपग्रेड करें',
    success:'सफलता', noData:'कोई डेटा नहीं', receipt:'रसीद',
    // Extra new keys
    emailAddress:'ईमेल पता', signIn:'साइन इन करें',
    signInToAccount:'अपने CharityOrg खाते में साइन इन करें',
    createFreeAccount:'मुफ्त खाता बनाएं', alreadyAccount:'पहले से खाता है?',
    viewCampaigns:'अभियान देखें', viewAllCampaigns:'सभी अभियान देखें',
    raised:'जुटाया', goal:'लक्ष्य', daysLeft:'दिन बाकी',
    totalDonors:'कुल दाताएं', volunteers:'स्वयंसेवक',
    browseCampaigns:'अभियान ब्राउज़ करें', getStarted:'अभी शुरू करें',
    ourMission:'हमारा मिशन', ourValues:'हमारे मूल्य',
    meetThe:'मिलें', team:'टीम', allCampaigns:'सभी अभियान',
    chooseCause:'एक कारण चुनें', newestFirst:'नवीनतम पहले',
    mostFunded:'सबसे अधिक वित्त पोषित', showing:'दिखाया जा रहा है', of:'में से',
    noCampaignsFound:'कोई अभियान नहीं मिला', tryAdjust:'खोज या फ़िल्टर समायोजित करें',
    viewAndDonate:'देखें और दान करें', myPlan:'मेरी योजना',
    userId:'उपयोगकर्ता ID', mobile:'मोबाइल', role:'भूमिका',
    clear:'साफ़ करें', profileDesc:'अपनी व्यक्तिगत जानकारी प्रबंधित करें',
    editPersonalDetails:'व्यक्तिगत विवरण संपादित करें',
    saving:'सहेज रहे हैं', viewAllDonations:'सभी दान देखें',
    totalDonations:'कुल दान', successful:'सफल',
    totalContributed:'कुल योगदान',
    trackContributions:'अपने योगदान ट्रैक करें', donations:'दान',
    quickLinks:'त्वरित लिंक', forDonors:'दाताओं के लिए',
    days:'दिन', verified:'सत्यापित', amount:'राशि',
    campaign:'अभियान', method:'विधि', date:'तारीख',
    donationSummary:'दान सारांश', accountDetails:'खाता विवरण',
    managePlan:'योजना प्रबंधित करें',
    campaignsBacked:'समर्थित अभियान',
    changeLines:'जिंदगी बदलें',
    everyRupee:'हर रुपये से', youGive:'जो आप देते हैं', all:'सभी',
    // New keys
    accountVerified:'खाता सत्यापित!', redirectingToDashboard:'आपको डैशबोर्ड पर ले जाया जा रहा है…',
    backToRegister:'← पंजीकरण पर वापस', backToLogin:'← लॉगिन पर वापस',
    verifyYourMobile:'अपना मोबाइल सत्यापित करें', verifyYourEmail:'अपना ईमेल सत्यापित करें',
    verifyYourIdentity:'अपनी पहचान सत्यापित करें',
    enterCodeSentToChannel:'भेजा गया 6-अंकीय कोड दर्ज करें',
    verificationRequiredOnce:'यह सत्यापन केवल एक बार आवश्यक है',
    verifying:'सत्यापित कर रहे हैं…', verifyActivateAccount:'✓ सत्यापित करें और खाता सक्रिय करें',
    verifySignIn:'✓ सत्यापित करें और साइन इन करें',
    enterMoreDigits:'दर्ज करें', moreDigits:'और अंक',
    didNotReceiveCode:'कोड नहीं मिला?', resendIn:'फिर भेजें',
    resendOtp:'↺ OTP दोबारा भेजें', weSentCodeTo:'6-अंकीय कोड भेजा गया',
    expiresIn5Min:'⏱ 5 मिनट में समाप्त', max3Attempts:'🔄 अधिकतम 3 प्रयास',
    oneTimeOnly:'🔑 केवल एक बार', checkYourInbox:'📧 अपना इनबॉक्स देखें',
    accessDenied:'पहुंच अस्वीकृत', noPermissionToView:'आपको इस पृष्ठ को देखने की अनुमति नहीं है।',
    goHome:'होम पर जाएं', backToCampaigns:'← अभियानों पर वापस',
    urgency:'तात्कालिकता', startDate:'प्रारंभ तिथि', endDate:'समाप्ति तिथि',
    beneficiaries:'लाभार्थी', createdBy:'द्वारा बनाया', remaining:'शेष',
    supportCampaign:'इस अभियान का समर्थन करें',
    loginAsDonorToDonate:'दान करने के लिए दाता के रूप में लॉगिन करें।',
    loginToDonate:'दान करने के लिए लॉगिन करें', registerAsDonor:'दाता के रूप में पंजीकरण करें',
    securePaymentViaRazorpay:'Razorpay के माध्यम से सुरक्षित भुगतान',
    receiptAutoGenerated:'80G रसीद स्वचालित रूप से उत्पन्न', transparentFundUsage:'100% पारदर्शी धन उपयोग',
    welcomeTo:'स्वागत है', howLikeToContribute:'आप कैसे योगदान करना चाहते हैं? कभी भी बदल सकते हैं।',
    generalDonorDesc:'जब चाहें एकमुश्त दान करें। कोई आवर्ती भुगतान नहीं।',
    oneTimeDonations:'एकमुश्त दान', noRecurringCharges:'कोई आवर्ती शुल्क नहीं',
    donateAnyCampaign:'किसी भी अभियान को दान', fullDonationHistory:'पूर्ण दान इतिहास',
    settingUp:'सेट कर रहे हैं…', continueAsGeneralDonor:'सामान्य दाता के रूप में जारी रखें',
    recommended:'अनुशंसित',
    monthlyGivingDesc:'मासिक दान सेट करें। स्वचालित, सुसंगत प्रभाव।',
    automaticMonthlyDonations:'स्वचालित मासिक दान',
    monthlyReceipts:'मासिक रसीदें', pauseResumeAnytime:'कभी भी रोकें/जारी रखें',
    cancelAnytime:'कभी भी रद्द करें', setUpMonthlyGiving:'मासिक दान सेट करें',
    setUpMonthlyGivingTitle:'मासिक दान सेट करें',
    chooseMonthlyAmount:'अपनी मासिक राशि, दान तिथि और अभियान चुनें।',
    minimumMonthlyAmountInfo:'न्यूनतम ₹50/माह', donationDayOfMonth:'दान का दिन',
    dayOfEveryMonth:'हर महीने का {day}वां दिन', campaignOptional:'अभियान (वैकल्पिक)',
    supportAllActiveCampaigns:'— सभी सक्रिय अभियानों का समर्थन करें —',
    monthlyGivingSummary:'आपका मासिक दान सारांश',
    monthlyGivingSummaryDesc:'हर महीने के {day}वें दिन दान किया जाएगा',
    toCampaign:'को', acrossActiveCampaigns:'सक्रिय अभियानों में',
    skipGoGeneral:'छोड़ें, सामान्य दाता बनें',
    activating:'सक्रिय कर रहे हैं…', activateMonthlyGiving:'मासिक दान सक्रिय करें',
    skipForNowDecideLater:'अभी छोड़ें — बाद में निर्णय लें',
    subscription:'सदस्यता', management:'प्रबंधन',
    manageDonationPlanPreferences:'अपनी दान योजना प्रबंधित करें',
    active:'सक्रिय', paused:'रोका गया', cancelled:'रद्द',
    generalDonorDescShort:'एकमुश्त दान — कोई आवर्ती शुल्क नहीं',
    upgradeToMonthlyGiving:'मासिक दान में अपग्रेड करें', month:'महीना',
    allActiveCampaigns:'सभी सक्रिय अभियान', dayOfMonth:'{day}वां दिन',
    nextDonation:'अगला दान', lastDonation:'अंतिम दान', notYet:'अभी नहीं',
    manageSubscription:'सदस्यता प्रबंधित करें', editAmount:'राशि संपादित करें',
    changeDate:'तिथि बदलें', pauseSubscription:'सदस्यता रोकें',
    resumeSubscription:'सदस्यता फिर शुरू करें', cancelSubscription:'सदस्यता रद्द करें',
    whyMonthlyGiving:'मासिक दान क्यों?', automatedDonations:'स्वचालित दान',
    noNeedToRemember:'याद रखने की जरूरत नहीं — हम संभालते हैं।',
    emailReminderBeforeDonation:'हर दान से पहले ईमेल अनुस्मारक।',
    automaticReceipts:'स्वचालित 80G कर रसीदें।',
    fullControl:'पूर्ण नियंत्रण', pauseResumeCancelAnytime:'कभी भी रोकें, जारी रखें या रद्द करें।',
    upgradeMonthlyDesc:'अपनी मासिक राशि और पसंदीदा तिथि सेट करें।',
    donationDay:'दान का दिन', editMonthlyAmount:'मासिक राशि संपादित करें',
    newMonthlyAmount:'नई मासिक राशि', updateAmount:'राशि अपडेट करें',
    changeDonationDate:'दान तिथि बदलें', newDonationDay:'नया दान दिन', updateDate:'तिथि अपडेट करें',
    payment:'भुगतान', offlineDemoModeInfo:'ऑफलाइन डेमो मोड — कोई वास्तविक भुगतान नहीं',
    donateToCampaign:'अभियान को दान', selectAmount:'राशि चुनें (₹)',
    customAmountPlaceholder:'या कस्टम राशि दर्ज करें',
    continueSelectPayment:'जारी रखें → भुगतान चुनें',
    choosePaymentMethod:'भुगतान विधि चुनें',
    donatingTo:'{campaign} को {amount} दान कर रहे हैं',
    demoModeNoRealCharge:'डेमो मोड — कोई वास्तविक शुल्क नहीं',
    paymentsSecuredByRazorpay:'Razorpay द्वारा सुरक्षित भुगतान।',
    processing:'प्रसंस्करण…', payDemo:'{amount} का भुगतान करें (डेमो)',
    paySecurely:'{amount} सुरक्षित भुगतान करें 🔒',
    receiptThankYou:'धन्यवाद, {name}! आपकी उदारता फर्क करती है। 💜',
    receiptNo:'रसीद नं.', transactionId:'लेनदेन ID', dateTime:'तिथि और समय',
    paymentConfirmed:'भुगतान की पुष्टि हुई', taxExempt80G:'80G छूट',
    taxDeductibleYes:'हां — कर कटौती योग्य', saveYourReceipt:'अपनी रसीद सहेजें',
    saveReceiptPrompt:'क्या आप अपनी दान रसीद का स्क्रीनशॉट सहेजना चाहते हैं?',
    savedDownloadAgain:'✓ सहेजा गया! फिर से डाउनलोड करें',
    yesSaveReceiptScreenshot:'हां, रसीद स्क्रीनशॉट सहेजें',
    receiptSavedDownloadsFolder:'रसीद आपके डाउनलोड फ़ोल्डर में सहेजी गई',
    donateAgain:'फिर से दान करें', thankYou:'धन्यवाद!',
    donationToConfirmed:'{campaign} को आपका दान की पुष्टि हो गई।',
    receiptSentToEmail:'रसीद {receipt} आपके ईमेल पर भेज दी गई।',
    viewMyDonations:'मेरे दान देखें', backToDashboard:'डैशबोर्ड पर वापस',
    upi:'UPI', creditCard:'क्रेडिट कार्ड', debitCard:'डेबिट कार्ड', netBanking:'नेट बैंकिंग',
    contactSubtitle:'हम आपसे सुनना चाहते हैं। कभी भी संपर्क करें!',
    loggedInAs:'{name} के रूप में लॉग इन हैं',
    messageLinkedToAccount:'आपका संदेश आपके खाते से जुड़ा होगा।',
    savePhoneAddressToProfile:'फ़ोन और पता प्रोफ़ाइल में सहेजें',
    tenDigitNumber:'10 अंकीय नंबर', addressCity:'पता / शहर', cityState:'शहर, राज्य',
    // Password change
    changePassword:'पासवर्ड बदलें',
    changePasswordDesc:'अपना पासवर्ड अपडेट करें। प्रत्येक परिवर्तन के बाद ईमेल पुष्टि भेजी जाएगी।',
    currentPassword:'वर्तमान पासवर्ड', currentPasswordPlaceholder:'आपका वर्तमान पासवर्ड',
    newPassword:'नया पासवर्ड', confirmNewPassword:'नया पासवर्ड पुष्टि करें',
    reEnterNewPassword:'नया पासवर्ड फिर से दर्ज करें',
    passwordsMatch:'पासवर्ड मेल खाते हैं',
    passwordRequirements:'न्यूनतम 8 अक्षर: बड़े, छोटे, संख्या और विशेष अक्षर',
    updatePassword:'पासवर्ड अपडेट करें',
    preferredLanguage:'पसंदीदा भाषा',
  },
  te: {
    home:'హోమ్', campaigns:'ప్రచారాలు', about:'గురించి', contact:'సంప్రదించండి',
    login:'లాగిన్', logout:'లాగ్ అవుట్', register:'నమోదు',
    dashboard:'డాష్‌బోర్డ్', myDonations:'నా విరాళాలు', profile:'ప్రొఫైల్',
    welcomeBack:'తిరిగి స్వాగతం', signIn:'సైన్ ఇన్', createAccount:'ఖాతా సృష్టించు',
    password:'పాస్‌వర్డ్', fullName:'పూర్తి పేరు', address:'చిరునామా',
    donateNow:'విరాళం ఇవ్వండి', details:'వివరాలు', cancel:'రద్దు చేయి',
    notifications:'నోటిఫికేషన్లు', loading:'లోడ్ అవుతోంది…',
    error:'లోపం జరిగింది', save:'సేవ్ చేయి', back:'వెనక్కి',
    total:'మొత్తం', amount:'మొత్తం', date:'తేదీ', status:'స్థితి',
    monthlyGiving:'నెలవారీ విరాళం', generalDonor:'సాధారణ దాత',
  },
  ml: {
    home:'ഹോം', campaigns:'കാമ്പെയ്‌നുകൾ', about:'ഞങ്ങളെ കുറിച്ച്', contact:'ബന്ധപ്പെടുക',
    login:'ലോഗിൻ', logout:'ലോഗ് ഔട്ട്', register:'രജിസ്ടർ ചെയ്യൂ',
    dashboard:'ഡാഷ്‌ബോർഡ്', myDonations:'എന്റെ സംഭാവനകൾ', profile:'പ്രൊഫൈൽ',
    welcomeBack:'സ്വാഗതം', signIn:'സൈൻ ഇൻ', createAccount:'അക്കൗണ്ട് ഉണ്ടാക്കൂ',
    password:'പാസ്‌വേഡ്', fullName:'പൂർണ്ണ നാമം', address:'വിലാസം',
    donateNow:'സംഭാവന ചെയ്യൂ', details:'വിവരങ്ങൾ', cancel:'റദ്ദാക്കൂ',
    notifications:'അറിയിപ്പുകൾ', loading:'ലോഡ് ആകുന്നു…',
    error:'പിഴവ് സംഭവിച്ചു', save:'സേവ് ചെയ്യൂ', back:'തിരിച്ചു',
    total:'ആകെ', amount:'തുക', date:'തീയതി', status:'നില',
    monthlyGiving:'മാസ സംഭാവന', generalDonor:'പൊതു ദാതാവ്',
  },
  kn: {
    home:'ಮುಖಪುಟ', campaigns:'ಅಭಿಯಾನಗಳು', about:'ನಮ್ಮ ಬಗ್ಗೆ', contact:'ಸಂಪರ್ಕಿಸಿ',
    login:'ಲಾಗಿನ್', logout:'ಲಾಗ್ ಔಟ್', register:'ನೋಂದಾಯಿಸಿ',
    dashboard:'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', myDonations:'ನನ್ನ ದೇಣಿಗೆಗಳು', profile:'ಪ್ರೊಫೈಲ್',
    welcomeBack:'ಮತ್ತೆ ಸ್ವಾಗತ', signIn:'ಸೈನ್ ಇನ್', createAccount:'ಖಾತೆ ತೆರೆಯಿರಿ',
    password:'ಪಾಸ್‌ವರ್ಡ್', fullName:'ಪೂರ್ಣ ಹೆಸರು', address:'ವಿಳಾಸ',
    donateNow:'ದೇಣಿಗೆ ನೀಡಿ', details:'ವಿವರಗಳು', cancel:'ರದ್ದುಮಾಡಿ',
    notifications:'ಅಧಿಸೂಚನೆಗಳು', loading:'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    error:'ದೋಷ ಸಂಭವಿಸಿದೆ', save:'ಉಳಿಸಿ', back:'ಹಿಂದೆ',
    total:'ಒಟ್ಟು', amount:'ಮೊತ್ತ', date:'ದಿನಾಂಕ', status:'ಸ್ಥಿತಿ',
    monthlyGiving:'ಮಾಸಿಕ ದೇಣಿಗೆ', generalDonor:'ಸಾಮಾನ್ಯ ದಾನಿ',
  },
};

export function LanguageProvider({ children }) {
  const [lang,    setLang]    = useState(() => localStorage.getItem('preferredLang') || 'en');
  const [labels,  setLabels]  = useState(EN_LABELS);
  const [loading, setLoading] = useState(false);
  const [userId,  setUserId]  = useState(null);

  // Watch for user login
  useEffect(() => {
    const checkUser = () => {
      try {
        const stored = localStorage.getItem('auth_user');
        const u      = stored ? JSON.parse(stored) : null;
        const uid    = u?.userId || null;
        if (uid !== userId) {
          setUserId(uid);
          if (uid) {
            axiosInstance.get('/api/language/preference')
              .then(r => {
                const sl = r.data?.data?.language || 'en';
                if (sl !== lang) {
                  setLang(sl);
                  localStorage.setItem('preferredLang', sl);
                }
              }).catch(() => {});
          }
        }
      } catch {}
    };
    checkUser();
    window.addEventListener('storage', checkUser);
    return () => window.removeEventListener('storage', checkUser);
  }, [userId, lang]);

  // Apply translations whenever lang changes
  useEffect(() => {
    applyTranslations(lang);
  }, [lang]); // eslint-disable-line

  const applyTranslations = useCallback(async (targetLang) => {
    if (targetLang === 'en') {
      setLabels(EN_LABELS);
      return;
    }

    // Step 1: Apply built-in static translations immediately (no API call needed)
    const staticTrans = STATIC_TRANSLATIONS[targetLang];
    if (staticTrans) {
      // Merge: static translations override English for matched keys
      const merged = { ...EN_LABELS, ...staticTrans };
      setLabels(merged);
    }

    // Step 2: Try Gemini for richer translation (async, non-blocking)
    setLoading(true);
    try {
      const r = await axiosInstance.post('/api/language/translate-bundle', {
        texts: EN_LABELS,
        language: targetLang,
      });
      const translated = r.data?.data;
      if (translated && Object.keys(translated).length > 0) {
        setLabels(translated);
      }
    } catch {
      // Keep static translations — no change needed
    } finally {
      setLoading(false);
    }
  }, []);

  const changeLanguage = useCallback(async (newLang) => {
    setLang(newLang);
    localStorage.setItem('preferredLang', newLang);
    try {
      const stored = localStorage.getItem('auth_user');
      if (stored) {
        axiosInstance.post('/api/language/preference', { language: newLang }).catch(() => {});
      }
    } catch {}
  }, []);

  const t = useCallback((key) => labels[key] || EN_LABELS[key] || key, [labels]);

  return (
    <LanguageContext.Provider value={{ lang, labels, t, changeLanguage, loading, SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
